#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Data;
    using System.Collections.Generic;
    using System.Reflection;
    using System.Linq;
    using System.Linq.Expressions;
    using System.ComponentModel;
    using System;
    using ENTITY;

    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Digital_Support")]
	public partial class DigitalSupportDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertORDENTRABAJO(ORDENTRABAJO instance);
    partial void UpdateORDENTRABAJO(ORDENTRABAJO instance);
    partial void DeleteORDENTRABAJO(ORDENTRABAJO instance);
    #endregion
		
		public DigitalSupportDBDataContext() : 
				base(global::DAL.Properties.Settings.Default.Digital_SupportConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DigitalSupportDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DigitalSupportDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DigitalSupportDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DigitalSupportDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ORDENTRABAJO> ORDENTRABAJO
		{
			get
			{
				return this.GetTable<ORDENTRABAJO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDENTRABAJO")]
	public partial class ORDENTRABAJO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ticket;
		
		private System.Nullable<int> _ID_asunto;
		
		private string _Desc_ticket;
		
		private System.Nullable<System.DateTime> _Fecha_creacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ticketChanging(int value);
    partial void OnID_ticketChanged();
    partial void OnID_asuntoChanging(System.Nullable<int> value);
    partial void OnID_asuntoChanged();
    partial void OnDesc_ticketChanging(string value);
    partial void OnDesc_ticketChanged();
    partial void OnFecha_creacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_creacionChanged();
    #endregion
		
		public ORDENTRABAJO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ticket", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_ticket
		{
			get
			{
				return this._ID_ticket;
			}
			set
			{
				if ((this._ID_ticket != value))
				{
					this.OnID_ticketChanging(value);
					this.SendPropertyChanging();
					this._ID_ticket = value;
					this.SendPropertyChanged("ID_ticket");
					this.OnID_ticketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_asunto", DbType="Int")]
		public System.Nullable<int> ID_asunto
		{
			get
			{
				return this._ID_asunto;
			}
			set
			{
				if ((this._ID_asunto != value))
				{
					this.OnID_asuntoChanging(value);
					this.SendPropertyChanging();
					this._ID_asunto = value;
					this.SendPropertyChanged("ID_asunto");
					this.OnID_asuntoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Desc_ticket", DbType="NVarChar(350)")]
		public string Desc_ticket
		{
			get
			{
				return this._Desc_ticket;
			}
			set
			{
				if ((this._Desc_ticket != value))
				{
					this.OnDesc_ticketChanging(value);
					this.SendPropertyChanging();
					this._Desc_ticket = value;
					this.SendPropertyChanged("Desc_ticket");
					this.OnDesc_ticketChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_creacion
		{
			get
			{
				return this._Fecha_creacion;
			}
			set
			{
				if ((this._Fecha_creacion != value))
				{
					this.OnFecha_creacionChanging(value);
					this.SendPropertyChanging();
					this._Fecha_creacion = value;
					this.SendPropertyChanged("Fecha_creacion");
					this.OnFecha_creacionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

        public static explicit operator ORDENTRABAJO(OrdenTrabajo v)
        {
            throw new NotImplementedException();
        }
    }
}
#pragma warning restore 1591
